name: Gitleaks-GHA-unofficial

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  secrets-detection:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Run Gitleaks
        id: gitleaks
        uses: DariuszPorowski/github-action-gitleaks@v2
        with:
          report_format: sarif

      - name: Upload SARIF report to Workflow Artifacts
        uses: actions/upload-artifact@v3
        if: always() && steps.gitleaks.outputs.exitcode != 0
        with:
          name: gitleaks
          path: |
            ${{ steps.gitleaks.outputs.report }}

      # Only for Organizations that use GitHub Enterprise Cloud and have a license for GitHub Advanced Security.
      - name: Upload SARIF report to Code Scanning service
        if: always() && steps.gitleaks.outputs.exitcode != 0
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.gitleaks.outputs.report }}
          category: gitleaks